<a href="https://colab.research.google.com/github/Syamchand123/pytorch_handson/blob/main/pytorch_handson(training_pipeline%2Cnn_module).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv')
df.tail()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
564  926424         M  ...                  0.07115          NaN
565  926682         M  ...                  0.06637          NaN
566  926954         M  ...                  0.07820          NaN
567  927241         M  ...                  0.12400          NaN
568   92751         B  ...                  0.07039          NaN

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.shape

(569, 31)

In [ ]:
x_train ,x_test ,y_train ,y_test =train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [ ]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [ ]:
#convert all numpy arrays into totch tensors
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)


**working on building neural network form scrath**


In [ ]:
class Myneuralnetwork():
  def __init__(self,x):
    torch.manual_seed(100)
    self.weights = torch.rand(x.shape[1],dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,x):
    z=torch.matmul(x,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred


  def calculateloss(self,y_pred,y):
    ep=1e-7
    y_pred=torch.clamp(y_pred,ep,1-ep)
    loss=-(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) *torch.log(1-y_pred)).mean()
    return loss

In [ ]:
#parameters
learning_rate=0.1
epochs=10

**pipeline**


In [ ]:
#create model
model=Myneuralnetwork(x_train_tensor)


for epoch in range(epochs):
 #forward pass
 y_pred=model.forward(x_train_tensor)

 #calculate loss
 Loss=model.calculateloss(y_pred,y_train_tensor)

 #backward propagation
 Loss.backward()

 #updating parameters
 with torch.no_grad():
  model.weights -= learning_rate *model.weights.grad
  model.bias -= learning_rate*model.bias.grad

 #zero grads
 model.weights.grad.zero_()
 model.bias.grad.zero_()


 #print loss in each
 print(f'Epoch: {epoch+1} , Loss : {Loss.item()}')


Epoch: 1 , Loss : 0.5891057169720805
Epoch: 2 , Loss : 0.5735239560989944
Epoch: 3 , Loss : 0.558330974045147
Epoch: 4 , Loss : 0.5435166125891989
Epoch: 5 , Loss : 0.5290717660120788
Epoch: 6 , Loss : 0.5149884197775831
Epoch: 7 , Loss : 0.5012597181469229
Epoch: 8 , Loss : 0.4878800527237114
Epoch: 9 , Loss : 0.4748451529260745
Epoch: 10 , Loss : 0.462152144928354


In [ ]:
model.weights

tensor([0.9563, 0.1587, 0.4684, 0.1575, 0.5897, 0.9067, 0.6647, 0.3443, 0.9022,
        0.6500, 0.4328, 0.4054, 0.5489, 0.9757, 0.8409, 0.1048, 0.2428, 0.0540,
        0.5470, 0.1657, 0.1966, 0.2545, 0.6050, 0.4145, 0.2116, 0.5275, 0.6321,
        0.9798, 0.5154, 0.1664], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([-0.0272], dtype=torch.float64, requires_grad=True)

**Evaluation**

In [ ]:
with torch.no_grad():
  y_pred=model.forward(x_test_tensor)
  y_pred=(y_pred > 0.5).float()

y_pred

tensor([1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
        0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0.,
        0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 1., 1.,
        1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0.,
        0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1.,
        0., 0., 1., 0., 0., 1.])

In [ ]:
#y_pred=(y_pred > 0.9).float()
accuracy =(y_pred == y_test_tensor).float().mean()
print(f'accuracy: {accuracy.item()}')

accuracy: 0.9122806787490845


✅



```
using torch nn module
```





In [1]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [9]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [10]:
df.shape

(569, 31)

In [11]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [19]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)

In [20]:
encode=LabelEncoder()
y_train=encode.fit_transform(y_train)
y_test=encode.fit_transform(y_test)

In [37]:
x_train_tensor=torch.from_numpy(x_train)
x_test_tensor=torch.from_numpy(x_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [119]:
#parameters
learning_rate=0.1
epochs=200

In [95]:
#design model
class Myneuralnet(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.net=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.net(features)
    return out



In [120]:
#instance model and required funtions
model=Myneuralnet(x_train_tensor.shape[1])
model = model.double()
Loss_funtion=nn.BCELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)

for epoch in range(epochs):
  # call model
  y_pred=model(x_train_tensor)


  #calculate loss
  Loss=Loss_funtion(y_pred,y_train_tensor.view(-1,1).double())

  #clear gradients
  optimizer.zero_grad()


  #backward propagation
  Loss.backward()


  #optimizer
  optimizer.step()


  #print loss in each
  print(f'Epoch: {epoch+1} , Loss : {Loss.item()}')




Epoch: 1 , Loss : 0.6113851637991644
Epoch: 2 , Loss : 0.5929463285606575
Epoch: 3 , Loss : 0.5743274755894772
Epoch: 4 , Loss : 0.5557348701745726
Epoch: 5 , Loss : 0.5374307238364298
Epoch: 6 , Loss : 0.5193604463713837
Epoch: 7 , Loss : 0.5018819086480367
Epoch: 8 , Loss : 0.4846818580298839
Epoch: 9 , Loss : 0.4678345482456354
Epoch: 10 , Loss : 0.45125435865131197
Epoch: 11 , Loss : 0.43522343727767027
Epoch: 12 , Loss : 0.4196952837337294
Epoch: 13 , Loss : 0.4046941281640126
Epoch: 14 , Loss : 0.39019985350568276
Epoch: 15 , Loss : 0.3762620154591301
Epoch: 16 , Loss : 0.3629260934396173
Epoch: 17 , Loss : 0.35028298879989406
Epoch: 18 , Loss : 0.3383160131294921
Epoch: 19 , Loss : 0.32691135523261206
Epoch: 20 , Loss : 0.3159546003403779
Epoch: 21 , Loss : 0.30556974275055593
Epoch: 22 , Loss : 0.2957381536856315
Epoch: 23 , Loss : 0.2864392123829195
Epoch: 24 , Loss : 0.277613072808991
Epoch: 25 , Loss : 0.26924005883846835
Epoch: 26 , Loss : 0.26131905160499636
Epoch: 27 , Lo

In [121]:
#model evaluation
with torch.no_grad():
  y_pred_test=model(x_test_tensor)
  y_pred_test=(y_pred_test > 0.5).float()
  # Ensure y_test_tensor matches the shape and type of y_pred_test for explicit comparison
  y_test_tensor_formatted = y_test_tensor.float().unsqueeze(1)
  accuracy=(y_pred_test == y_test_tensor_formatted).float().mean()
  print(accuracy.item())

0.9561403393745422


In [107]:
!pip install torchinfo

In [122]:
from torchinfo import summary
summary(model)

Layer (type:depth-idx)                   Param #
Myneuralnet                              --
├─Sequential: 1-1                        --
│    └─Linear: 2-1                       93
│    └─ReLU: 2-2                         --
│    └─Linear: 2-3                       4
│    └─Sigmoid: 2-4                      --
Total params: 97
Trainable params: 97
Non-trainable params: 0